### ISSUE TITLE
wrong screen resolution 

### ISSUE THREAD

**Issue by kalingkx** [ryenyuku/twrp_device_infinix_x692#1]
wrong touch and can't mount partitions...there fore cant do backup nor install..You just port it on hova-auto porter 1.8a ?

**Comment by ryenyuku** [comment]
The touch screen issue is a known issue that yet I can't find a solution for now. And I'm able to mount the partitions and do backup & install, so it's only happening on your end only. (What firmware version are you using?)

Also no, I'm not porting it by just repacking the image. It's entirely compiled from the source

**Comment by kalingkx** [comment]
latest version dude...
![Screenshot_20220408-061913](https://user-images.githubusercontent.com/101184501/162329889-d5783b1c-4e67-4087-a7e1-ad2075fb079a.png)

**Comment by ryenyuku** [comment]
Can you provide some further info about the partition mounting problem? Because it's not happening in my end and I'm not a wizard that can magically fix your problems

**Comment by ryenyuku** [comment]
I'll try bumping it with the latest firmware, since it's based on older firmware

**Comment by kalingkx** [comment]
its a redlines saying unable to mount system partition ..sorry sir i cant provide SS bcoz last night i restored my IN8..but here is the latest stock recovery image pulled by infinityCM2....  
https://dropmb.com/ZVase

**Comment by kalingkx** [comment]
backup failed
![Screenshot_2022-04-08-14-59-37](https://user-images.githubusercontent.com/101184501/162518648-19c3a068-84fb-4331-83ac-e8de4dc12709.png)

**Comment by ryenyuku** [comment]
Sorry for the late reply, but unfortunately it's an expected behaviour when you use newer firmware. Since Android is using F2FS for the /data partition, you can't mount the partition that has been formatted in newer kernel on old kernel.
The only solution is to use the new kernel on twrp

(For more info, you can look at this https://bugs.archlinux.org/task/69363)

**Comment by kalingkx** [comment]
i wanna try your ported twrp ..pls.. spexify.what firmware version it will work. tyz..
  i can downgrade my phone so i have a custom rec....

**Comment by ryenyuku** [comment]
The touch screen and the /data partition mount issue should be fixed in the latest commit, please wait until it has finished compiling the twrp ;)

**Comment by ryenyuku** [comment]
https://github.com/ryenyuku/twrp_device_infinix_x692/releases/tag/v3.6.1-2
